Repository 2025-SW-Capstone-Design/Back-End, pull requests merged in 2025-05, with the labels that each got.

#86 [Chore] 배포 설정 관련 수정
  src/main/java/soon/capstone/global/security/oauth2/handler/OAuth2SuccessHandler.java
  src/main/resources/application.yml
Labels: Chore

#88 [Feat] 사용자의 팀 목록 조회 API 구현
  src/main/java/soon/capstone/domain/team/controller/TeamController.java
  src/main/java/soon/capstone/domain/team/service/dto/response/TeamDetailResponse.java
  src/main/java/soon/capstone/domain/team/service/team/TeamReaderService.java
  src/main/java/soon/capstone/domain/team/service/team/TeamService.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberJpaRepository.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberRepository.java
  src/test/java/soon/capstone/domain/team/controller/TeamControllerTest.java
  src/test/java/soon/capstone/domain/team/service/team/TeamReaderServiceTest.java
Labels: Feat

#90 [Fix] Cors 오류
  src/main/java/soon/capstone/global/security/config/SecurityConfig.java
Labels: Fix

#94 [Feat] 프로젝트 생성 시 이슈 라벨 연동 기능 구현
  src/main/java/soon/capstone/domain/issue/service/IssueLabelService.java
  src/main/java/soon/capstone/domain/project/repository/ProjectJpaRepository.java
  src/main/java/soon/capstone/domain/project/repository/ProjectRepository.java
  src/main/java/soon/capstone/domain/project/service/ProjectService.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelServiceTest.java
  src/test/java/soon/capstone/domain/project/service/ProjectServiceTest.java
Labels: Feat

#95 [Feat] 화상회의 기능 구현
  build.gradle
  src/main/java/soon/capstone/domain/chatroom/controller/ChatRoomController.java
  src/main/java/soon/capstone/domain/chatroom/controller/ChatRoomTeamMemberController.java
  src/main/java/soon/capstone/domain/chatroom/controller/dto/ChatRoomAddMemberRequest.java
  src/main/java/soon/capstone/domain/chatroom/controller/dto/ChatRoomCreateRequest.java
  src/main/java/soon/capstone/domain/chatroom/controller/dto/request/ChatRoomResumeRequest.java
  src/main/java/soon/capstone/domain/chatroom/entity/ChatRoom.java
  src/main/java/soon/capstone/domain/chatroom/entity/ChatRoomTeamMember.java
  src/main/java/soon/capstone/domain/chatroom/repository/ChatRoomJpaRepository.java
  src/main/java/soon/capstone/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/soon/capstone/domain/chatroom/repository/ChatRoomTeamMemberJpaRepository.java
  src/main/java/soon/capstone/domain/chatroom/repository/ChatRoomTeamMemberRepository.java
  src/main/java/soon/capstone/domain/chatroom/service/ChatRoomService.java
  src/main/java/soon/capstone/domain/chatroom/service/ChatRoomTeamMemberService.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/request/ChatRoomAddMemberServiceRequest.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/request/ChatRoomCreateServiceRequest.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/request/ChatRoomFinishServiceRequest.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/request/ChatRoomResumeServiceRequest.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberJpaRepository.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberRepository.java
  src/main/java/soon/capstone/domain/teammember/service/TeamMemberValidator.java
  src/main/java/soon/capstone/global/exception/chatroom/ChatRoomNotFoundException.java
  src/main/java/soon/capstone/global/exception/chatroom/ChatRoomTeamMemberNotFoundException.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/infrastructure/openvidu/config/OpenViduWebhookConfig.java
  src/main/java/soon/capstone/infrastructure/openvidu/controller/OpenViduController.java
  src/main/java/soon/capstone/infrastructure/openvidu/controller/dto/request/OpenViduGenerateTokenRequest.java
  src/main/java/soon/capstone/infrastructure/openvidu/controller/dto/request/OpenViduWebhookEventRequest.java
  src/main/java/soon/capstone/infrastructure/openvidu/handler/OpenViduWebhookEventHandler.java
  src/main/java/soon/capstone/infrastructure/openvidu/handler/ParticipantJoinedEventHandler.java
  src/main/java/soon/capstone/infrastructure/openvidu/handler/RoomFinishedEventHandler.java
  src/main/java/soon/capstone/infrastructure/openvidu/handler/RoomStartedEventHandler.java
  src/main/java/soon/capstone/infrastructure/openvidu/mapper/OpenViduWebhookEventMapper.java
  src/main/java/soon/capstone/infrastructure/openvidu/service/OpenViduApiService.java
  src/main/java/soon/capstone/infrastructure/openvidu/service/dto/request/OpenViduGenerateTokenServiceRequest.java
  src/main/java/soon/capstone/infrastructure/openvidu/service/dto/request/OpenViduWebhookEventServiceRequest.java
  src/main/java/soon/capstone/infrastructure/openvidu/service/dto/response/OpenViduGenerateTokenResponse.java
  src/test/java/soon/capstone/ControllerTestSupport.java
  src/test/java/soon/capstone/domain/chatroom/controller/ChatRoomControllerTest.java
  src/test/java/soon/capstone/domain/chatroom/controller/ChatRoomTeamMemberControllerTest.java
  src/test/java/soon/capstone/domain/chatroom/service/ChatRoomServiceTest.java
  src/test/java/soon/capstone/domain/chatroom/service/ChatRoomTeamMemberServiceTest.java
  src/test/java/soon/capstone/infrastructure/openvidu/controller/OpenViduControllerTest.java
  src/test/java/soon/capstone/infrastructure/openvidu/service/OpenViduApiServiceTest.java
Labels: Feat

#98 [Fix] 이슈 라벨 초기 세팅 관련 오류 수정
  src/main/java/soon/capstone/domain/project/repository/ProjectJpaRepository.java
  src/main/java/soon/capstone/domain/project/repository/ProjectRepository.java
  src/main/java/soon/capstone/domain/project/service/ProjectService.java
  src/test/java/soon/capstone/domain/project/service/ProjectServiceTest.java
Labels: Fix

#100 [Refacotr] initializeIssueLabels 트랜잭션 범위 재 설정 및 로깅 추가
  src/main/java/soon/capstone/domain/issue/service/IssueLabelService.java
  src/main/java/soon/capstone/domain/project/service/ProjectService.java
  src/main/java/soon/capstone/infrastructure/github/service/issue/GithubIssueLabelService.java
Labels: Refactor

#101 [Feat] 채팅방 조회 기능 구현
  src/main/java/soon/capstone/domain/chatroom/controller/ChatRoomController.java
  src/main/java/soon/capstone/domain/chatroom/controller/ChatRoomTeamMemberController.java
  src/main/java/soon/capstone/domain/chatroom/controller/dto/ChatRoomDetailsRequest.java
  src/main/java/soon/capstone/domain/chatroom/controller/dto/ChatRoomTeamMembersDetailRequest.java
  src/main/java/soon/capstone/domain/chatroom/entity/ChatRoom.java
  src/main/java/soon/capstone/domain/chatroom/repository/ChatRoomTeamMemberJpaRepository.java
  src/main/java/soon/capstone/domain/chatroom/repository/chatroom/ChatRoomJpaRepository.java
  src/main/java/soon/capstone/domain/chatroom/repository/chatroom/ChatRoomListRepository.java
  src/main/java/soon/capstone/domain/chatroom/repository/chatroom/ChatRoomListRepositoryImpl.java
  src/main/java/soon/capstone/domain/chatroom/repository/chatroom/ChatRoomRepository.java
  src/main/java/soon/capstone/domain/chatroom/repository/member/ChatRoomTeamMemberJpaRepository.java
  src/main/java/soon/capstone/domain/chatroom/repository/member/ChatRoomTeamMemberRepository.java
  src/main/java/soon/capstone/domain/chatroom/service/ChatRoomService.java
  src/main/java/soon/capstone/domain/chatroom/service/ChatRoomTeamMemberService.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/request/ChatRoomDetailsServiceRequest.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/request/ChatRoomGetMembersServiceRequest.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/request/ChatRoomTeamMembersDetailServiceRequest.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/response/ChatRoomDetailsResponse.java
  src/test/java/soon/capstone/domain/chatroom/controller/ChatRoomControllerTest.java
  src/test/java/soon/capstone/domain/chatroom/controller/ChatRoomTeamMemberControllerTest.java
  src/test/java/soon/capstone/domain/chatroom/repository/chatroom/ChatRoomListRepositoryImplTest.java
  src/test/java/soon/capstone/domain/chatroom/service/ChatRoomServiceTest.java
  src/test/java/soon/capstone/domain/chatroom/service/ChatRoomTeamMemberServiceTest.java
Labels: Feat

#103 [Fix] issueLabel update 로직 수정
  src/main/java/soon/capstone/domain/issue/service/IssueLabelService.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelServiceTest.java
Labels: Fix

#106 [Feat] 마감일이 다가온 마일스톤 조회 기능 구현
  src/main/java/soon/capstone/domain/issue/service/dto/response/IssueDetailResponse.java
  src/main/java/soon/capstone/domain/milestone/controller/MilestoneController.java
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneCustomRepository.java
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneCustomRepositoryImpl.java
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneJpaRepository.java
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneListRepositoryImpl.java
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneRepository.java
  src/main/java/soon/capstone/domain/milestone/service/MilestoneReadService.java
  src/main/java/soon/capstone/domain/milestone/service/MilestoneService.java
  src/main/java/soon/capstone/domain/milestone/service/dto/response/MilestoneIssueResponse.java
  src/test/java/soon/capstone/domain/milestone/controller/MilestoneControllerTest.java
  src/test/java/soon/capstone/domain/milestone/repository/MilestoneCustomRepositoryImplTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneReadServiceTest.java
Labels: Feat

#108 [Refactor] 마일스톤 상태 enum 변경
  src/main/java/soon/capstone/domain/milestone/entity/Milestone.java
  src/main/java/soon/capstone/domain/milestone/entity/MilestoneStatus.java
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneCustomRepositoryImpl.java
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneListRepositoryImpl.java
  src/main/java/soon/capstone/domain/milestone/service/MilestoneCreationService.java
  src/main/java/soon/capstone/domain/milestone/service/MilestoneReadService.java
  src/main/java/soon/capstone/domain/milestone/service/MilestoneUpdateService.java
  src/main/java/soon/capstone/domain/milestone/service/dto/MilestoneCreationDto.java
  src/main/java/soon/capstone/domain/milestone/service/dto/response/MilestoneDetailResponse.java
  src/main/java/soon/capstone/domain/milestone/service/dto/response/MilestoneResponse.java
  src/main/java/soon/capstone/infrastructure/github/dto/request/GithubMilestoneUpdateDto.java
  src/main/java/soon/capstone/infrastructure/github/service/milestone/GithubMilestoneUpdateService.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelRelationServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueManagementServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueServiceTest.java
  src/test/java/soon/capstone/domain/milestone/controller/MilestoneControllerTest.java
  src/test/java/soon/capstone/domain/milestone/repository/MilestoneCustomRepositoryImplTest.java
  src/test/java/soon/capstone/domain/milestone/repository/MilestoneListRepositoryImplTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneCreationServiceTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneReadServiceTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneServiceTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneUpdateServiceTest.java
Labels: Refactor

#112 [Fix] Milestone DB 저장 오류
  src/main/java/soon/capstone/domain/milestone/service/MilestoneCreationService.java
Labels: Fix

#114 [Fix] Milestone 제목 중복 검사 오류
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneJpaRepository.java
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneRepository.java
  src/main/java/soon/capstone/domain/milestone/service/MilestoneCreationService.java
Labels: Fix

#115 [Feat] 마일스톤 상태 변경 기능 구현
  src/main/java/soon/capstone/domain/milestone/controller/MilestoneController.java
  src/main/java/soon/capstone/domain/milestone/controller/dto/MilestoneStatusUpdateRequest.java
  src/main/java/soon/capstone/domain/milestone/entity/Milestone.java
  src/main/java/soon/capstone/domain/milestone/service/MilestoneService.java
  src/main/java/soon/capstone/domain/milestone/service/MilestoneUpdateService.java
  src/main/java/soon/capstone/domain/milestone/service/dto/request/MilestoneStatusUpdateServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/milestone/GithubMilestoneUpdateService.java
  src/test/java/soon/capstone/domain/milestone/controller/MilestoneControllerTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneUpdateServiceTest.java
Labels: Feat

#117 [Fix] IssueTemplate 팀을 찾지 못하는 오류
  src/main/java/soon/capstone/domain/issue/controller/IssueTemplateController.java
Labels: Fix

#121 [Fix] IssueRelation 오류
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelRepository.java
  src/main/java/soon/capstone/domain/issue/service/IssueLabelRelationService.java
  src/main/java/soon/capstone/domain/issue/service/IssueService.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelRelationServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueServiceTest.java
Labels: Fix

#127 [Fix] 이슈 라벨 수정 시 키 중복 문제
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelRepository.java
  src/main/java/soon/capstone/domain/issue/service/IssueLabelRelationService.java
  src/main/java/soon/capstone/domain/issue/service/IssueService.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelRelationServiceTest.java
Labels: Fix

#129 [Feat] issue reopen 기능 구현
  src/main/java/soon/capstone/domain/issue/controller/IssueController.java
  src/main/java/soon/capstone/domain/issue/controller/docs/IssueControllerDocs.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueClosedRequest.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueUpdateStatusRequest.java
  src/main/java/soon/capstone/domain/issue/entity/Issue.java
  src/main/java/soon/capstone/domain/issue/entity/IssueStatus.java
  src/main/java/soon/capstone/domain/issue/service/IssueManagementService.java
  src/main/java/soon/capstone/domain/issue/service/IssueService.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueUpdateStatusServiceRequest.java
  src/test/java/soon/capstone/domain/issue/controller/IssueControllerTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueManagementServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueServiceTest.java
Labels: Feat

#131 [Refactor] 채팅방 생성 로직 변경
  src/main/java/soon/capstone/domain/chatroom/controller/dto/ChatRoomCreateRequest.java
  src/main/java/soon/capstone/domain/chatroom/entity/ChatRoom.java
  src/main/java/soon/capstone/domain/chatroom/repository/chatroom/ChatRoomJpaRepository.java
  src/main/java/soon/capstone/domain/chatroom/repository/chatroom/ChatRoomRepository.java
  src/main/java/soon/capstone/domain/chatroom/service/ChatRoomService.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/request/ChatRoomCreateServiceRequest.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/response/ChatRoomDetailsResponse.java
  src/main/java/soon/capstone/global/exception/chatroom/ChatRoomAlreadyExistsForTeamException.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/infrastructure/openvidu/controller/dto/request/OpenViduWebhookEventRequest.java
  src/main/java/soon/capstone/infrastructure/openvidu/handler/RoomStartedEventHandler.java
  src/main/java/soon/capstone/infrastructure/openvidu/mapper/OpenViduWebhookEventMapper.java
  src/main/java/soon/capstone/infrastructure/openvidu/service/dto/request/OpenViduWebhookEventServiceRequest.java
  src/test/java/soon/capstone/domain/chatroom/controller/ChatRoomControllerTest.java
  src/test/java/soon/capstone/domain/chatroom/repository/chatroom/ChatRoomListRepositoryImplTest.java
  src/test/java/soon/capstone/domain/chatroom/service/ChatRoomServiceTest.java
  src/test/java/soon/capstone/domain/chatroom/service/ChatRoomTeamMemberServiceTest.java
  src/test/java/soon/capstone/infrastructure/openvidu/controller/OpenViduControllerTest.java
  src/test/java/soon/capstone/infrastructure/openvidu/service/OpenViduApiServiceTest.java
Labels: Refactor

#134 [Refactor] 엔티티 content 컬럼 변경
  src/main/java/soon/capstone/domain/issue/entity/Issue.java
  src/main/java/soon/capstone/domain/issue/entity/IssueTemplate.java
  src/main/java/soon/capstone/domain/meetinglog/entity/MeetingLog.java
  src/main/java/soon/capstone/domain/portfolio/entity/Portfolio.java
  src/main/java/soon/capstone/domain/readme/entity/Readme.java
Labels: Refactor

#135 [Refactor] 화상채팅 웹훅 이벤트 감지방식 변경
  src/main/java/soon/capstone/global/exception/chatroom/TemporaryRoomIdentityNotFoundException.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/infrastructure/openvidu/controller/OpenViduController.java
  src/main/java/soon/capstone/infrastructure/openvidu/controller/dto/request/OpenViduWebhookEventRequest.java
  src/main/java/soon/capstone/infrastructure/openvidu/handler/ParticipantJoinedEventHandler.java
  src/main/java/soon/capstone/infrastructure/openvidu/handler/RoomFinishedEventHandler.java
  src/main/java/soon/capstone/infrastructure/openvidu/handler/TrackPublishedEventHandler.java
  src/main/java/soon/capstone/infrastructure/openvidu/handler/TrackUnpublishedEventHandler.java
  src/main/java/soon/capstone/infrastructure/openvidu/service/OpenViduApiService.java
  src/main/java/soon/capstone/infrastructure/redis/openvidu/entity/TemporaryRoomIdentity.java
  src/main/java/soon/capstone/infrastructure/redis/openvidu/repository/TemporaryRoomIdentityRedisRepository.java
  src/main/java/soon/capstone/infrastructure/redis/openvidu/repository/TemporaryRoomIdentityRepository.java
Labels: Refactor

#138 [Feat] 회의록 요약 기능 구현
  src/main/java/soon/capstone/domain/chatroom/controller/ChatRoomController.java
  src/main/java/soon/capstone/domain/chatroom/controller/dto/ChatRoomSummarizeRequest.java
  src/main/java/soon/capstone/domain/chatroom/service/ChatRoomService.java
  src/main/java/soon/capstone/domain/chatroom/service/dto/request/ChatRoomSummarizeServiceRequest.java
  src/main/java/soon/capstone/domain/meetinglog/entity/MeetingLog.java
  src/main/java/soon/capstone/domain/meetinglog/repository/MeetingLogRepository.java
  src/main/java/soon/capstone/domain/meetinglog/service/MeetingLogService.java
  src/main/java/soon/capstone/domain/meetinglog/service/dto/request/MeetingLogCreateServiceRequest.java
  src/main/java/soon/capstone/infrastructure/openai/common/PromptType.java
  src/main/java/soon/capstone/infrastructure/openai/service/GptSummaryService.java
  src/main/java/soon/capstone/infrastructure/openai/service/dto/OpenAiResponse.java
  src/main/java/soon/capstone/infrastructure/openai/service/dto/request/GptSummaryServiceRequest.java
  src/main/java/soon/capstone/infrastructure/openvidu/handler/RoomFinishedEventHandler.java
  src/main/java/soon/capstone/infrastructure/redis/summary/entity/SummaryText.java
  src/main/java/soon/capstone/infrastructure/redis/summary/repository/SummaryTextRedisRepository.java
  src/main/java/soon/capstone/infrastructure/redis/summary/repository/SummaryTextRepository.java
  src/main/java/soon/capstone/infrastructure/redis/summary/service/SummaryTextService.java
  src/main/java/soon/capstone/infrastructure/restclient/config/RestClientConfig.java
  src/main/resources/application.yml
  src/test/java/soon/capstone/domain/chatroom/controller/ChatRoomControllerTest.java
  src/test/java/soon/capstone/domain/chatroom/service/ChatRoomServiceTest.java
  src/test/java/soon/capstone/domain/meetinglog/service/MeetingLogServiceTest.java
  src/test/java/soon/capstone/infrastructure/redis/summary/repository/SummaryTextRepositoryTest.java
Labels: Feat

#140 [Feat] 회의록 관련 기능 구현
  src/main/java/soon/capstone/domain/meetinglog/controller/MeetingLogController.java
  src/main/java/soon/capstone/domain/meetinglog/controller/dto/MeetingLogUpdateRequest.java
  src/main/java/soon/capstone/domain/meetinglog/entity/MeetingLog.java
  src/main/java/soon/capstone/domain/meetinglog/repository/MeetingLogJpaRepository.java
  src/main/java/soon/capstone/domain/meetinglog/repository/MeetingLogRepository.java
  src/main/java/soon/capstone/domain/meetinglog/service/MeetingLogService.java
  src/main/java/soon/capstone/domain/meetinglog/service/dto/request/MeetingLogUpdateServiceRequest.java
  src/main/java/soon/capstone/domain/meetinglog/service/dto/response/MeetingLogDetailResponse.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/meetinglog/MeetingLogNotFoundException.java
  src/test/java/soon/capstone/ControllerTestSupport.java
  src/test/java/soon/capstone/domain/meetinglog/controller/MeetingLogControllerTest.java
  src/test/java/soon/capstone/domain/meetinglog/service/MeetingLogServiceTest.java
Labels: Feat

#143 [Fix] Cors 문제 해결
  src/main/java/soon/capstone/global/security/config/SecurityConfig.java
Labels: Fix

#145 [Fix] 이슈 상태 변경 시 assignees 추가
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueUpdateStatusRequest.java
  src/main/java/soon/capstone/domain/issue/service/IssueManagementService.java
  src/main/java/soon/capstone/domain/issue/service/IssueService.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueUpdateStatusServiceRequest.java
  src/test/java/soon/capstone/domain/issue/service/IssueManagementServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueServiceTest.java
Labels: Fix
