Repository 2025-SW-Capstone-Design/Back-End, pull requests merged in 2025-04, with the labels that each got.

#52 [Feat] 이슈 라벨 관련 기능 구현
  src/main/java/soon/capstone/domain/issue/controller/IssueLabelController.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueLabelDeleteRequest.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueLabelDetailRequest.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelRepository.java
  src/main/java/soon/capstone/domain/issue/service/IssueLabelService.java
  src/main/java/soon/capstone/domain/issue/service/IssueManagementService.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueLabelDeleteServiceRequest.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueLabelDetailServiceRequest.java
  src/main/java/soon/capstone/domain/issue/service/dto/response/IssueLabelDetailResponse.java
  src/main/java/soon/capstone/infrastructure/github/dto/GithubIssueLabelDetailDto.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueLabelDeleteServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueLabelDetailServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/issue/GithubIssueLabelService.java
  src/main/java/soon/capstone/infrastructure/redis/config/RedisCacheConfig.java
  src/test/java/soon/capstone/domain/issue/controller/IssueLabelControllerTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueManagementServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueTemplateServiceTest.java
Labels: Feat

#54 [Feat] 리드미 기능 구현
  src/main/java/soon/capstone/domain/readme/controller/ReadmeController.java
  src/main/java/soon/capstone/domain/readme/controller/dto/request/ReadmeCreateRequest.java
  src/main/java/soon/capstone/domain/readme/controller/dto/request/ReadmeDeleteRequest.java
  src/main/java/soon/capstone/domain/readme/controller/dto/request/ReadmeDetailRequest.java
  src/main/java/soon/capstone/domain/readme/controller/dto/request/ReadmeRollbackRequest.java
  src/main/java/soon/capstone/domain/readme/controller/dto/request/ReadmeUpdateRequest.java
  src/main/java/soon/capstone/domain/readme/controller/dto/request/ReadmesListRequest.java
  src/main/java/soon/capstone/domain/readme/entity/Readme.java
  src/main/java/soon/capstone/domain/readme/repository/ReadmeJpaRepository.java
  src/main/java/soon/capstone/domain/readme/repository/ReadmeRepository.java
  src/main/java/soon/capstone/domain/readme/service/ReadmeService.java
  src/main/java/soon/capstone/domain/readme/service/dto/request/ReadmeCreateServiceRequest.java
  src/main/java/soon/capstone/domain/readme/service/dto/request/ReadmeDeleteServiceRequest.java
  src/main/java/soon/capstone/domain/readme/service/dto/request/ReadmeDetailServiceRequest.java
  src/main/java/soon/capstone/domain/readme/service/dto/request/ReadmeRollbackServiceRequest.java
  src/main/java/soon/capstone/domain/readme/service/dto/request/ReadmeUpdateServiceRequest.java
  src/main/java/soon/capstone/domain/readme/service/dto/request/ReadmesListServiceRequest.java
  src/main/java/soon/capstone/domain/readme/service/dto/response/ReadmeDetailResponse.java
  src/main/java/soon/capstone/domain/readme/service/dto/response/ReadmeListResponse.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/readme/ReadmeNotFoundException.java
  src/test/java/soon/capstone/ControllerTestSupport.java
  src/test/java/soon/capstone/domain/project/service/RepositoryCreationServiceTest.java
  src/test/java/soon/capstone/domain/readme/controller/ReadmeControllerTest.java
  src/test/java/soon/capstone/domain/readme/service/ReadmeServiceTest.java
Labels: Feat

#56 [Feat] 이슈 생성 기능 구현
  src/main/java/soon/capstone/domain/issue/controller/IssueController.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueCreateRequest.java
  src/main/java/soon/capstone/domain/issue/entity/Issue.java
  src/main/java/soon/capstone/domain/issue/entity/IssueStatus.java
  src/main/java/soon/capstone/domain/issue/repository/issue/IssueRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issueLabelRelation/IssueLabelRelationJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issueLabelRelation/IssueLabelRelationRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelRepository.java
  src/main/java/soon/capstone/domain/issue/service/AssigneeService.java
  src/main/java/soon/capstone/domain/issue/service/IssueLabelRelationService.java
  src/main/java/soon/capstone/domain/issue/service/IssueManagementService.java
  src/main/java/soon/capstone/domain/issue/service/IssueService.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueCreateServiceRequest.java
  src/main/java/soon/capstone/domain/teammember/entity/TeamMember.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/issue/issue/IssueNotFoundException.java
  src/main/java/soon/capstone/infrastructure/github/dto/request/GithubAssigneesAppendRequest.java
  src/main/java/soon/capstone/infrastructure/github/dto/request/GithubIssueLabelAppendRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubAssigneesAppendServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueCreateServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueLabelAppendServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/response/GithubIssueCreateResponse.java
  src/main/java/soon/capstone/infrastructure/github/service/issue/GithubAssigneesService.java
  src/main/java/soon/capstone/infrastructure/github/service/issue/GithubIssueLabelService.java
  src/main/java/soon/capstone/infrastructure/github/service/issue/GithubIssueService.java
  src/main/java/soon/capstone/infrastructure/redis/config/RedisCacheConfig.java
  src/test/java/soon/capstone/ControllerTestSupport.java
  src/test/java/soon/capstone/domain/issue/controller/IssueControllerTest.java
  src/test/java/soon/capstone/domain/issue/service/AssigneeServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelRelationServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueManagementServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueServiceTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneReadServiceTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneServiceTest.java
Labels: Feat

#60 [Chore] 불필요한 파일 삭제
  .gitignore
  .idea/codeStyles/codeStyleConfig.xml
Labels: Chore

#63 [Feat] 마일스톤 스케줄러 기능 구현
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneListRepository.java
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneListRepositoryImpl.java
  src/main/java/soon/capstone/domain/milestone/repository/MilestoneRepository.java
  src/main/java/soon/capstone/domain/milestone/service/MilestoneMailService.java
  src/main/java/soon/capstone/domain/milestone/service/MilestoneScheduler.java
  src/main/java/soon/capstone/domain/milestone/service/dto/MilestoneMailDto.java
  src/main/java/soon/capstone/domain/project/repository/ProjectRepository.java
  src/main/java/soon/capstone/domain/team/repository/TeamRepository.java
  src/main/java/soon/capstone/global/config/SchedulerConfig.java
  src/main/java/soon/capstone/global/email/service/EmailSendService.java
  src/test/java/soon/capstone/domain/milestone/repository/MilestoneListRepositoryImplTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneMailServiceTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneSchedulerTest.java
  src/test/java/soon/capstone/global/email/service/EmailSendServiceTest.java
Labels: Feat

#65 [Feat] 이슈 관련 기능 구현
  src/main/java/soon/capstone/domain/issue/controller/IssueController.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueClosedRequest.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueDetailListRequest.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueDetailRequest.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueUpdateRequest.java
  src/main/java/soon/capstone/domain/issue/entity/Issue.java
  src/main/java/soon/capstone/domain/issue/entity/IssueLabelRelation.java
  src/main/java/soon/capstone/domain/issue/repository/issue/IssueJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issue/IssueListRepositoryImpl.java
  src/main/java/soon/capstone/domain/issue/repository/issue/IssueRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issueLabelRelation/IssueLabelRelationJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issueLabelRelation/IssueLabelRelationRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelRepository.java
  src/main/java/soon/capstone/domain/issue/service/AssigneeService.java
  src/main/java/soon/capstone/domain/issue/service/IssueLabelRelationService.java
  src/main/java/soon/capstone/domain/issue/service/IssueLabelService.java
  src/main/java/soon/capstone/domain/issue/service/IssueManagementService.java
  src/main/java/soon/capstone/domain/issue/service/IssueService.java
  src/main/java/soon/capstone/domain/issue/service/dto/ScopeType.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueClosedServiceRequest.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueDetailListServiceRequest.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueDetailServiceRequest.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueUpdateServiceRequest.java
  src/main/java/soon/capstone/domain/issue/service/dto/response/IssueDetailResponse.java
  src/main/java/soon/capstone/domain/issue/service/dto/response/IssueLabelDetailResponse.java
  src/main/java/soon/capstone/infrastructure/github/dto/request/GithubIssueUpdateRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueDetailListServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueDetailServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueUpdateServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/response/GithubIssueDetailResponse.java
  src/main/java/soon/capstone/infrastructure/github/service/issue/GithubIssueService.java
  src/main/java/soon/capstone/infrastructure/redis/config/RedisCacheConfig.java
  src/test/java/soon/capstone/domain/issue/controller/IssueControllerTest.java
  src/test/java/soon/capstone/domain/issue/controller/IssueLabelControllerTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelRelationServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueManagementServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueServiceTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneReadServiceTest.java
  src/test/java/soon/capstone/domain/milestone/service/MilestoneServiceTest.java
Labels: Feat

#67 [Feat] 로드밸런서를 위한 HealthController 구현
  src/main/java/soon/capstone/infrastructure/common/HealthController.java
Labels: Feat

#69 [Docs] API 명세화 작업
  src/main/java/soon/capstone/domain/auth/controller/AuthController.java
  src/main/java/soon/capstone/domain/auth/controller/docs/AuthControllerDocs.java
  src/main/java/soon/capstone/domain/issue/controller/IssueController.java
  src/main/java/soon/capstone/domain/issue/controller/IssueLabelController.java
  src/main/java/soon/capstone/domain/issue/controller/IssueTemplateController.java
  src/main/java/soon/capstone/domain/issue/controller/docs/IssueControllerDocs.java
  src/main/java/soon/capstone/domain/issue/controller/docs/IssueLabelControllerDocs.java
  src/main/java/soon/capstone/domain/issue/controller/docs/IssueTemplateControllerDocs.java
  src/main/java/soon/capstone/domain/milestone/controller/MilestoneController.java
  src/main/java/soon/capstone/domain/milestone/controller/docs/MilestoneControllerDocs.java
  src/main/java/soon/capstone/domain/portfolio/controller/PortfolioController.java
  src/main/java/soon/capstone/domain/portfolio/controller/docs/PortfolioControllerDocs.java
  src/main/java/soon/capstone/domain/project/controller/ProjectController.java
  src/main/java/soon/capstone/domain/project/controller/docs/ProjectControllerDocs.java
  src/main/java/soon/capstone/domain/readme/controller/ReadmeController.java
  src/main/java/soon/capstone/domain/readme/controller/docs/ReadmeControllerDocs.java
  src/main/java/soon/capstone/domain/team/controller/TeamController.java
  src/main/java/soon/capstone/domain/team/controller/docs/TeamControllerDocs.java
  src/main/java/soon/capstone/domain/teammember/controller/TeamMemberController.java
  src/main/java/soon/capstone/domain/teammember/controller/docs/TeamMemberControllerDocs.java
Labels: Docs

#71 [Chore] HealthController Endpoint 수정
  src/main/java/soon/capstone/infrastructure/common/HealthController.java
Labels: Chore

#73 [Feat] CI/CD 작업
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  src/main/resources/application.yml
Labels: Feat

#77 [Fix] getIssuesWithRepository Redis 역직렬화 에러 수정
  src/main/java/soon/capstone/infrastructure/redis/config/RedisCacheConfig.java
  src/test/java/soon/capstone/domain/issue/service/IssueServiceTest.java
Labels: Fix

#79 [Chore] HealthController 엔드포인트 관련 수정
  src/main/java/soon/capstone/global/security/config/SecurityConfig.java
Labels: Chore

#81 [Chore] 배포 후 작업
  src/main/java/soon/capstone/global/security/config/SecurityConfig.java
  src/main/java/soon/capstone/global/security/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/soon/capstone/global/swagger/config/SwaggerConfig.java
Labels: Chore
