Repository 2025-SW-Capstone-Design/Back-End, pull requests merged in 2025-03, with the labels that each got.

#5 [Feat] Oauth2 깃허브 로그인 기능 구현
  build.gradle
  src/main/java/soon/capstone/domain/member/repository/MemberJpaRepository.java
  src/main/java/soon/capstone/domain/member/repository/MemberRepository.java
  src/main/java/soon/capstone/external/config/RestClientConfig.java
  src/main/java/soon/capstone/external/github/dto/GithubEmailDto.java
  src/main/java/soon/capstone/external/github/service/GithubEmailService.java
  src/main/java/soon/capstone/global/config/SecurityConfig.java
  src/main/java/soon/capstone/global/domain/token/common/TokenExpiration.java
  src/main/java/soon/capstone/global/domain/token/common/TokenType.java
  src/main/java/soon/capstone/global/domain/token/dto/response/TokenResponse.java
  src/main/java/soon/capstone/global/domain/token/filter/JWTAuthenticationFilter.java
  src/main/java/soon/capstone/global/domain/token/provider/JWTProvider.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/github/GithubMemberEmailNotFoundException.java
  src/main/java/soon/capstone/global/exception/github/PrimaryVerifiedEmailNotFoundException.java
  src/main/java/soon/capstone/global/oauth2/dto/CustomOAuth2Member.java
  src/main/java/soon/capstone/global/oauth2/handler/Oauth2FailureHandler.java
  src/main/java/soon/capstone/global/oauth2/handler/Oauth2SuccessHandler.java
  src/main/java/soon/capstone/global/oauth2/service/Oauth2GithubService.java
  src/main/java/soon/capstone/global/redis/domain/jwt/entity/JWTRefreshToken.java
  src/main/java/soon/capstone/global/redis/domain/jwt/repository/JwtRedisRepository.java
  src/main/java/soon/capstone/global/redis/domain/jwt/repository/JwtRepository.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/entity/OauthToken.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/repository/OauthTokenRedisRepository.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/repository/OauthTokenRepository.java
  src/main/resources/application.yml
  src/test/java/soon/capstone/global/domain/token/provider/JWTProviderTest.java
Labels: Feat

#7 [Fix] redis entity @id import문 변경
  src/main/java/soon/capstone/global/redis/domain/jwt/entity/JWTRefreshToken.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/entity/OauthToken.java
Labels: Fix

#9 [Chore] 네이밍 수정 및 로깅 메세지 수정
  src/main/java/soon/capstone/external/s3/provider/S3StorageProvider.java
  src/main/java/soon/capstone/global/config/SecurityConfig.java
  src/main/java/soon/capstone/global/domain/token/filter/JwtAuthenticationFilter.java
  src/main/java/soon/capstone/global/domain/token/provider/JwtProvider.java
  src/main/java/soon/capstone/global/exception/GlobalRestExceptionHandler.java
  src/main/java/soon/capstone/global/oauth2/dto/CustomOAuth2Member.java
  src/main/java/soon/capstone/global/oauth2/handler/OAuth2FailureHandler.java
  src/main/java/soon/capstone/global/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/soon/capstone/global/oauth2/service/OAuth2GithubService.java
  src/main/java/soon/capstone/global/redis/domain/jwt/entity/JwtRefreshToken.java
  src/main/java/soon/capstone/global/redis/domain/jwt/repository/JwtRedisRepository.java
  src/main/java/soon/capstone/global/redis/domain/jwt/repository/JwtRepository.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/entity/OAuthToken.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/repository/OAuthTokenRedisRepository.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/repository/OAuthTokenRepository.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/repository/OauthTokenRedisRepository.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/repository/OauthTokenRepository.java
  src/test/java/soon/capstone/global/domain/token/provider/JwtProviderTest.java
Labels: Chore

#11 [Feat] Jwt 재발급 기능 구현
  src/main/java/soon/capstone/domain/member/repository/MemberRepository.java
  src/main/java/soon/capstone/global/config/SecurityConfig.java
  src/main/java/soon/capstone/global/domain/auth/controller/AuthController.java
  src/main/java/soon/capstone/global/domain/auth/controller/dto/ReissueTokenRequest.java
  src/main/java/soon/capstone/global/domain/auth/service/AuthService.java
  src/main/java/soon/capstone/global/domain/auth/service/dto/request/ReissueTokenServiceRequest.java
  src/main/java/soon/capstone/global/exception/GlobalRestExceptionHandler.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/token/InvalidRefreshTokenException.java
  src/main/java/soon/capstone/global/exception/token/TokenNotFoundException.java
  src/main/java/soon/capstone/global/redis/domain/jwt/repository/JwtRedisRepository.java
  src/main/java/soon/capstone/global/redis/domain/jwt/repository/JwtRepository.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/entity/OAuthToken.java
  src/test/java/soon/capstone/ControllerTestSupport.java
  src/test/java/soon/capstone/TestSecurityConfig.java
  src/test/java/soon/capstone/global/domain/auth/controller/AuthControllerTest.java
  src/test/java/soon/capstone/global/domain/auth/service/AuthServiceTest.java
Labels: Feat

#15 [Fix] security 인증 문제
  src/main/java/soon/capstone/global/config/SecurityConfig.java
  src/main/java/soon/capstone/global/domain/token/filter/JwtAuthenticationFilter.java
  src/main/java/soon/capstone/global/domain/token/handler/JwtAccessDeniedHandler.java
  src/main/java/soon/capstone/global/domain/token/handler/JwtAuthenticationEntryPoint.java
  src/main/java/soon/capstone/global/domain/token/provider/JwtProvider.java
  src/main/java/soon/capstone/global/oauth2/handler/OAuth2SuccessHandler.java
Labels: Fix

#16 [Feat] 사용자 인증 커스텀 어노테이션 구현
  src/main/java/soon/capstone/global/anootation/AuthMemberId.java
  src/main/java/soon/capstone/global/anootation/AuthMemberIdResolver.java
  src/main/java/soon/capstone/global/config/WebConfig.java
  src/main/java/soon/capstone/global/exception/common/UnauthorizedException.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
Labels: Feat

#18 [Refactor] jwt 인증 정보 변경
  src/main/java/soon/capstone/domain/member/repository/MemberRepository.java
  src/main/java/soon/capstone/global/anootation/AuthMemberIdResolver.java
  src/main/java/soon/capstone/global/domain/auth/service/AuthService.java
  src/main/java/soon/capstone/global/domain/token/provider/JwtProvider.java
  src/main/java/soon/capstone/global/oauth2/handler/OAuth2SuccessHandler.java
  src/test/java/soon/capstone/global/domain/auth/service/AuthServiceTest.java
  src/test/java/soon/capstone/global/domain/token/provider/JwtProviderTest.java
Labels: Refactor

#20 [Feat] 팀 생성 및 초대 기능 구현
  build.gradle
  src/main/java/soon/capstone/domain/team/controller/TeamController.java
  src/main/java/soon/capstone/domain/team/controller/dto/TeamCreateRequest.java
  src/main/java/soon/capstone/domain/team/controller/dto/TeamInvitationRequest.java
  src/main/java/soon/capstone/domain/team/repository/TeamJpaRepository.java
  src/main/java/soon/capstone/domain/team/repository/TeamRepository.java
  src/main/java/soon/capstone/domain/team/service/InvitationCodeGenerator.java
  src/main/java/soon/capstone/domain/team/service/TeamService.java
  src/main/java/soon/capstone/domain/team/service/dto/request/TeamCreateServiceRequest.java
  src/main/java/soon/capstone/domain/team/service/dto/request/TeamInvitationServiceRequest.java
  src/main/java/soon/capstone/domain/teammember/entity/TeamMember.java
  src/main/java/soon/capstone/domain/teammember/entity/common/Position.java
  src/main/java/soon/capstone/domain/teammember/entity/common/Role.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberJpaRepository.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberRepository.java
  src/main/java/soon/capstone/external/github/dto/GithubOrganizationMembershipDto.java
  src/main/java/soon/capstone/external/github/service/GithubOrganizationService.java
  src/main/java/soon/capstone/global/config/EmailConfig.java
  src/main/java/soon/capstone/global/email/service/EmailSendService.java
  src/main/java/soon/capstone/global/exception/common/EmailSendException.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/team/InvitationCodeNotFoundException.java
  src/main/java/soon/capstone/global/exception/team/IsNotAdminInOrganizationException.java
  src/main/java/soon/capstone/global/exception/team/IsNotTeamLeaderException.java
  src/main/java/soon/capstone/global/exception/team/TeamAlreadyExistsException.java
  src/main/java/soon/capstone/global/exception/team/TeamNotFoundException.java
  src/main/java/soon/capstone/global/exception/teammember/AlreadyTeamMemberException.java
  src/main/java/soon/capstone/global/exception/teammember/TeamMemberNotFoundException.java
  src/main/java/soon/capstone/global/redis/domain/invitation/entity/InvitationCode.java
  src/main/java/soon/capstone/global/redis/domain/invitation/repository/InvitationCodeRedisRepository.java
  src/main/java/soon/capstone/global/redis/domain/invitation/repository/InvitationCodeRepository.java
  src/main/java/soon/capstone/global/redis/domain/oauth2/repository/OAuthTokenRepository.java
  src/main/resources/application.yml
  src/test/java/soon/capstone/ControllerTestSupport.java
  src/test/java/soon/capstone/TestSecurityContext.java
  src/test/java/soon/capstone/domain/team/controller/TeamControllerTest.java
  src/test/java/soon/capstone/domain/team/service/InvitationCodeGeneratorTest.java
  src/test/java/soon/capstone/domain/team/service/TeamServiceTest.java
  src/test/java/soon/capstone/global/anootation/TestMember.java
  src/test/java/soon/capstone/global/email/service/EmailSendServiceTest.java
Labels: Feat

#24 [Refactor] 팀 관련 기능 리펙토링
  src/main/java/soon/capstone/domain/auth/service/AuthService.java
  src/main/java/soon/capstone/domain/team/controller/TeamController.java
  src/main/java/soon/capstone/domain/team/controller/dto/TeamGenerateInvitationCodeRequest.java
  src/main/java/soon/capstone/domain/team/service/InvitationCodeGenerator.java
  src/main/java/soon/capstone/domain/team/service/TeamCreationService.java
  src/main/java/soon/capstone/domain/team/service/TeamInvitationService.java
  src/main/java/soon/capstone/domain/team/service/TeamService.java
  src/main/java/soon/capstone/domain/team/service/dto/request/TeamCreateServiceRequest.java
  src/main/java/soon/capstone/domain/team/service/dto/request/TeamGenerateInvitationCodeServiceRequest.java
  src/main/java/soon/capstone/infrastructure/redis/invitation/entity/InvitationCode.java
  src/main/java/soon/capstone/infrastructure/redis/invitation/repository/InvitationCodeRepository.java
  src/main/java/soon/capstone/infrastructure/redis/jwt/entity/JwtRefreshToken.java
  src/main/java/soon/capstone/infrastructure/redis/jwt/repository/JwtRedisRepository.java
  src/main/java/soon/capstone/infrastructure/redis/jwt/repository/JwtRepository.java
  src/main/java/soon/capstone/infrastructure/redis/oauth2/entity/OAuthToken.java
  src/main/java/soon/capstone/infrastructure/redis/oauth2/repository/OAuthTokenRedisRepository.java
  src/main/java/soon/capstone/infrastructure/redis/oauth2/repository/OAuthTokenRepository.java
  src/test/java/soon/capstone/domain/team/controller/TeamControllerTest.java
  src/test/java/soon/capstone/domain/team/service/InvitationCodeGeneratorTest.java
  src/test/java/soon/capstone/domain/team/service/TeamCreationServiceTest.java
  src/test/java/soon/capstone/domain/team/service/TeamInvitationServiceTest.java
  src/test/java/soon/capstone/domain/team/service/TeamServiceTest.java
Labels: Refactor

#26 [Feat] 팀 참여 기능 구현
  src/main/java/soon/capstone/domain/team/controller/TeamController.java
  src/main/java/soon/capstone/domain/team/controller/dto/TeamJoinRequest.java
  src/main/java/soon/capstone/domain/team/service/dto/request/TeamJoinServiceRequest.java
  src/main/java/soon/capstone/domain/team/service/invitation/InvitationCodeGenerator.java
  src/main/java/soon/capstone/domain/team/service/team/TeamCreationService.java
  src/main/java/soon/capstone/domain/team/service/team/TeamInvitationService.java
  src/main/java/soon/capstone/domain/team/service/team/TeamJoinService.java
  src/main/java/soon/capstone/domain/team/service/team/TeamService.java
  src/main/java/soon/capstone/domain/teammember/entity/TeamMember.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberJpaRepository.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberRepository.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/github/OAuthTokenExpiredException.java
  src/main/java/soon/capstone/infrastructure/github/service/GithubOrganizationService.java
  src/main/java/soon/capstone/infrastructure/redis/config/RedisConfig.java
  src/main/java/soon/capstone/infrastructure/redis/invitation/entity/InvitationCode.java
  src/main/java/soon/capstone/infrastructure/redis/invitation/repository/InvitationCodeRedisRepository.java
  src/main/java/soon/capstone/infrastructure/redis/invitation/repository/InvitationCodeRepository.java
  src/main/java/soon/capstone/infrastructure/redis/oauth2/repository/OAuthTokenRepository.java
  src/test/java/soon/capstone/ControllerTestSupport.java
  src/test/java/soon/capstone/domain/team/controller/TeamControllerTest.java
  src/test/java/soon/capstone/domain/team/service/invitation/InvitationCodeGeneratorTest.java
  src/test/java/soon/capstone/domain/team/service/team/TeamCreationServiceTest.java
  src/test/java/soon/capstone/domain/team/service/team/TeamInvitationServiceTest.java
  src/test/java/soon/capstone/domain/team/service/team/TeamJoinServiceTest.java
  src/test/java/soon/capstone/domain/team/service/team/TeamServiceTest.java
Labels: Feat

#28 [Feat] 팀 멤버 관련 기능 구현
  src/main/java/soon/capstone/domain/member/repository/MemberRepository.java
  src/main/java/soon/capstone/domain/teammember/controller/TeamMemberController.java
  src/main/java/soon/capstone/domain/teammember/controller/dto/TeamMemberUpdateRoleRequest.java
  src/main/java/soon/capstone/domain/teammember/entity/TeamMember.java
  src/main/java/soon/capstone/domain/teammember/entity/common/Role.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberJpaRepository.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberListRepository.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberListRepositoryImpl.java
  src/main/java/soon/capstone/domain/teammember/repository/TeamMemberRepository.java
  src/main/java/soon/capstone/domain/teammember/service/TeamMemberService.java
  src/main/java/soon/capstone/domain/teammember/service/dto/request/TeamMemberUpdateRoleServiceRequest.java
  src/main/java/soon/capstone/domain/teammember/service/dto/response/TeamMemberDetailResponse.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/team/TeamNotAuthorizedException.java
  src/test/java/soon/capstone/ControllerTestSupport.java
  src/test/java/soon/capstone/domain/team/controller/TeamControllerTest.java
  src/test/java/soon/capstone/domain/teammember/controller/TeamMemberControllerTest.java
  src/test/java/soon/capstone/domain/teammember/repository/TeamMemberListRepositoryImplTest.java
  src/test/java/soon/capstone/domain/teammember/service/TeamMemberServiceTest.java
Labels: Feat

#31 [Refactor] url 수정
  src/main/java/soon/capstone/domain/issue/controller/IssueController.java
  src/main/java/soon/capstone/domain/issue/controller/IssueLabelController.java
  src/main/java/soon/capstone/domain/issue/controller/IssueTemplateController.java
  src/main/java/soon/capstone/domain/team/controller/TeamController.java
  src/main/java/soon/capstone/domain/team/controller/dto/TeamGenerateInvitationCodeRequest.java
  src/main/java/soon/capstone/domain/team/controller/dto/TeamInvitationRequest.java
  src/main/java/soon/capstone/domain/team/service/dto/request/TeamGenerateInvitationCodeServiceRequest.java
  src/main/java/soon/capstone/domain/team/service/team/TeamService.java
  src/main/java/soon/capstone/domain/teammember/controller/TeamMemberController.java
  src/test/java/soon/capstone/domain/team/controller/TeamControllerTest.java
  src/test/java/soon/capstone/domain/team/service/team/TeamServiceTest.java
  src/test/java/soon/capstone/domain/teammember/controller/TeamMemberControllerTest.java
Labels: Refactor

#33 [Refactor] IssueLabel, Issue 연관관계 추가
  src/main/java/soon/capstone/domain/issue/entity/Issue.java
  src/main/java/soon/capstone/domain/issue/entity/IssueLabel.java
Labels: Refactor

#34 [Feat] Project 관련 기능 구현
  build.gradle
  src/main/java/soon/capstone/domain/project/controller/ProjectController.java
  src/main/java/soon/capstone/domain/project/repository/ProjectJpaRepository.java
  src/main/java/soon/capstone/domain/project/repository/ProjectListRepository.java
  src/main/java/soon/capstone/domain/project/repository/ProjectListRepositoryImpl.java
  src/main/java/soon/capstone/domain/project/repository/ProjectRepository.java
  src/main/java/soon/capstone/domain/project/service/OrganizationProjectCreationService.java
  src/main/java/soon/capstone/domain/project/service/ProjectReadService.java
  src/main/java/soon/capstone/domain/project/service/ProjectService.java
  src/main/java/soon/capstone/domain/project/service/RepositoryCreationService.java
  src/main/java/soon/capstone/domain/project/service/dto/request/TeamCreatedEvent.java
  src/main/java/soon/capstone/domain/project/service/dto/response/ProjectDetailResponse.java
  src/main/java/soon/capstone/domain/project/service/dto/response/RepositoryCreationEvent.java
  src/main/java/soon/capstone/domain/team/service/team/TeamCreationService.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/github/GithubHttpClientException.java
  src/main/java/soon/capstone/global/exception/project/ProjectNotFoundException.java
  src/main/java/soon/capstone/infrastructure/github/dto/GithubRepositoryCreationDto.java
  src/main/java/soon/capstone/infrastructure/github/service/GithubOrganizationReadService.java
  src/main/java/soon/capstone/infrastructure/github/service/GithubProjectCreationService.java
  src/main/java/soon/capstone/infrastructure/github/service/GithubRepositoryCreationService.java
  src/main/java/soon/capstone/infrastructure/github/service/constant/GithubQuery.java
  src/main/java/soon/capstone/infrastructure/graphQL/GraphQLClientConfig.java
  src/main/resources/application.yml
  src/test/java/soon/capstone/ControllerTestSupport.java
  src/test/java/soon/capstone/domain/project/controller/ProjectControllerTest.java
  src/test/java/soon/capstone/domain/project/service/OrganizationProjectCreationServiceTest.java
  src/test/java/soon/capstone/domain/project/service/ProjectReadServiceTest.java
  src/test/java/soon/capstone/domain/project/service/ProjectServiceTest.java
  src/test/java/soon/capstone/domain/project/service/RepositoryCreationServiceTest.java
Labels: Feat

#39 [Refactor] Issue 연관관계 변경
  src/main/java/soon/capstone/domain/issue/entity/Issue.java
  src/main/java/soon/capstone/domain/issue/entity/IssueLabelRelation.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelRelationJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelRelationRepository.java
Labels: Refactor

#40 [Feat] 이슈 라벨, 템플릿 생성 기능 구현
  src/main/java/soon/capstone/domain/issue/controller/IssueLabelController.java
  src/main/java/soon/capstone/domain/issue/controller/IssueTemplateController.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueLabelCreateRequest.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueTemplateCreateRequest.java
  src/main/java/soon/capstone/domain/issue/entity/IssueLabel.java
  src/main/java/soon/capstone/domain/issue/entity/IssueType.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuelabel/IssueLabelRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuetemplate/IssueTemplateJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuetemplate/IssueTemplateRepository.java
  src/main/java/soon/capstone/domain/issue/service/IssueLabelService.java
  src/main/java/soon/capstone/domain/issue/service/IssueManagementService.java
  src/main/java/soon/capstone/domain/issue/service/IssueTemplateService.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueLabelCreateServiceRequest.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueTemplateCreateServiceRequest.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/issue/label/AlreadyIssueLabelException.java
  src/main/java/soon/capstone/global/exception/issue/label/IssueLabelNotFoundException.java
  src/main/java/soon/capstone/global/exception/issue/template/AlreadyIssueTemplateException.java
  src/main/java/soon/capstone/global/exception/issue/template/IssueTemplateNotFoundException.java
  src/main/java/soon/capstone/infrastructure/github/dto/request/GithubIssueCreateRequest.java
  src/main/java/soon/capstone/infrastructure/github/dto/request/GithubIssueLabelCreateRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/GithubAssigneesService.java
  src/main/java/soon/capstone/infrastructure/github/service/GithubIssueLabelService.java
  src/main/java/soon/capstone/infrastructure/github/service/GithubIssueService.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubAssigneesServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueLabelServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueServiceRequest.java
  src/test/java/soon/capstone/ControllerTestSupport.java
  src/test/java/soon/capstone/domain/issue/controller/IssueLabelControllerTest.java
  src/test/java/soon/capstone/domain/issue/controller/IssueTemplateControllerTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueManagementServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueTemplateServiceTest.java
  src/test/java/soon/capstone/domain/project/service/OrganizationProjectCreationServiceTest.java
  src/test/java/soon/capstone/domain/project/service/ProjectReadServiceTest.java
  src/test/java/soon/capstone/domain/team/service/team/TeamCreationServiceTest.java
Labels: Feat

#42 [Fix] Project 생성 오류
  src/main/java/soon/capstone/domain/project/service/ProjectService.java
Labels: Fix

#46 [Chore] Github Service 패키지 구조 변경
  src/main/java/soon/capstone/domain/issue/service/IssueLabelService.java
  src/main/java/soon/capstone/domain/project/service/OrganizationProjectCreationService.java
  src/main/java/soon/capstone/domain/project/service/RepositoryCreationService.java
  src/main/java/soon/capstone/domain/team/service/team/TeamCreationService.java
  src/main/java/soon/capstone/domain/team/service/team/TeamJoinService.java
  src/main/java/soon/capstone/infrastructure/github/service/issue/GithubAssigneesService.java
  src/main/java/soon/capstone/infrastructure/github/service/issue/GithubIssueLabelService.java
  src/main/java/soon/capstone/infrastructure/github/service/issue/GithubIssueService.java
  src/main/java/soon/capstone/infrastructure/github/service/organization/GithubOrganizationReadService.java
  src/main/java/soon/capstone/infrastructure/github/service/organization/GithubOrganizationService.java
  src/main/java/soon/capstone/infrastructure/github/service/project/GithubLinkProjectToRepositoryService.java
  src/main/java/soon/capstone/infrastructure/github/service/project/GithubProjectCreationService.java
  src/main/java/soon/capstone/infrastructure/github/service/repository/GithubRepositoryCreationService.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelServiceTest.java
  src/test/java/soon/capstone/domain/project/service/OrganizationProjectCreationServiceTest.java
  src/test/java/soon/capstone/domain/project/service/RepositoryCreationServiceTest.java
  src/test/java/soon/capstone/domain/team/service/team/TeamCreationServiceTest.java
  src/test/java/soon/capstone/domain/team/service/team/TeamJoinServiceTest.java
Labels: Chore

#47 [Feat] 이슈 라벨 수정
  src/main/java/soon/capstone/domain/issue/controller/IssueLabelController.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueLabelUpdateRequest.java
  src/main/java/soon/capstone/domain/issue/entity/IssueLabel.java
  src/main/java/soon/capstone/domain/issue/service/IssueLabelService.java
  src/main/java/soon/capstone/domain/issue/service/IssueManagementService.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueLabelUpdateServiceRequest.java
  src/main/java/soon/capstone/global/exception/dto/ErrorDetail.java
  src/main/java/soon/capstone/global/exception/github/GithubIssueLabelNotFoundException.java
  src/main/java/soon/capstone/infrastructure/github/dto/request/GithubIssueLabelUpdateRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueLabelCreateServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/dto/GithubIssueLabelUpdateServiceRequest.java
  src/main/java/soon/capstone/infrastructure/github/service/issue/GithubIssueLabelService.java
  src/test/java/soon/capstone/domain/issue/controller/IssueLabelControllerTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueManagementServiceTest.java
Labels: Feat

#49 [Feat] 이슈 템플릿 관련 기능 구현
  src/main/java/soon/capstone/domain/issue/controller/IssueTemplateController.java
  src/main/java/soon/capstone/domain/issue/controller/dto/IssueTemplateUpdateRequest.java
  src/main/java/soon/capstone/domain/issue/entity/IssueTemplate.java
  src/main/java/soon/capstone/domain/issue/repository/issuetemplate/IssueTemplateJpaRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuetemplate/IssueTemplateListRepository.java
  src/main/java/soon/capstone/domain/issue/repository/issuetemplate/IssueTemplateListRepositoryImpl.java
  src/main/java/soon/capstone/domain/issue/repository/issuetemplate/IssueTemplateRepository.java
  src/main/java/soon/capstone/domain/issue/service/IssueManagementService.java
  src/main/java/soon/capstone/domain/issue/service/IssueTemplateService.java
  src/main/java/soon/capstone/domain/issue/service/dto/request/IssueTemplateUpdateServiceRequest.java
  src/main/java/soon/capstone/domain/issue/service/dto/response/IssueTemplateDetailResponse.java
  src/test/java/soon/capstone/domain/issue/controller/IssueTemplateControllerTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueLabelServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueManagementServiceTest.java
  src/test/java/soon/capstone/domain/issue/service/IssueTemplateServiceTest.java
Labels: Feat
